import type { Metadata } from "next";
import AuthProvider from "@/context/authProvider";
import { Toaster } from "@/components/ui/toaster"


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <body > 
        {children}
        <Toaster />
         </body>
      </AuthProvider>
    </html>
  );
}
